Areas/Identity/Pages/CreateAphorism.cshtml.cs
using ChuckNorrisAphorisms.Data.Entities;
using ChuckNorrisAphorisms.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Options;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;

namespace ChuckNorrisAphorisms.Areas.Identity.Pages.Account
{
    [Authorize]
    public class CreateAphorismModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IAphorismsService _aphorismsService;
        private readonly IConfiguration _configuration;
        private readonly IEmailSender _emailSender;
        private readonly EmailSenderOptions _emailSenderOptions;

        public class InputModel
        {
            [Required]
            public string Aphorism { get; set; }

            [Required]
            public string Culture { get; set; }
        }

        public List<SelectListItem> Cultures
        {
            get
            {
                var cultures = new List<SelectListItem>();

                foreach (var culture in _configuration.GetSection("SupportedCultures").GetChildren())
                {
                    cultures.Add(new SelectListItem
                    {
                        Value = culture.GetSection("Value").Value,
                        Text = culture.GetSection("Text").Value
                    });
                }
                return cultures;
            }
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public CreateAphorismModel(
            UserManager<ApplicationUser> userManager,
            IAphorismsService aphorismsService,
            IConfiguration configuration,
            IEmailSender emailSender,
            IOptions<EmailSenderOptions> emailSenderOptions)
        {
            _userManager = userManager;
            _aphorismsService = aphorismsService;
            _configuration = configuration;
            _emailSender = emailSender;
            _emailSenderOptions = emailSenderOptions.Value;
        }

        public void OnGet()
        {

        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid && !Input.Aphorism.ToLower().Contains("chuck norris"))
            {
                ModelState.AddModelError("Input.Aphorism", "Aphorism must contains \"Chuck Norris\"");
            }

            if (!ModelState.IsValid)
            {
                return Page();
            }

            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            // Avviso amministratore che un utente ha inserito una richiesta di aforisma
            await _emailSender.SendEmailAsync(_emailSenderOptions.AdministratorEmail, "New aphorism pending request",
            $"The user {user.UserName} send this aphorism:{Input.Aphorism}, to accept click here: {Url.Page("/ManagePendingAphorisms")}");

            await _aphorismsService.AddAphorism(Input.Aphorism, Input.Culture, user.Id, true, Data.Models.AphorismStatus.Pending);

            return RedirectToPage("ManageAphorisms");
        }
    }
}

Areas/Identity/Pages/ManageAphorisms.cshtml.cs
using ChuckNorrisAphorisms.Data.Entities;
using ChuckNorrisAphorisms.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ChuckNorrisAphorisms.Areas.Identity.Pages.Account
{
    [Authorize]
    public class ManageAphorismsModel : PageModel
    {
        private readonly IAphorismsService _aphorismsService;

        public ManageAphorismsModel(IAphorismsService aphorismsService)
        {
            _aphorismsService = aphorismsService;
        }

        public IEnumerable<Aphorism> PendingAphorisms { get; set; } = new List<Aphorism>();
        public IEnumerable<Aphorism> PublishedAphorisms { get; set; } = new List<Aphorism>();

        public bool CanAddAphorisms { get; set; }
        public ApplicationUser ApplicationUser { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            return Page();
        }
    }
}

Controllers/AphorismsController.cs
using ChuckNorrisAphorisms.Data;
using ChuckNorrisAphorisms.Data.Models;
using ChuckNorrisAphorisms.Services;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ChuckNorrisAphorisms.Controllers
{
    [ApiController]
    [Route("api/aphorism")]
    public class AphorismsController : ControllerBase
    {
        private readonly ILogger<AphorismsController> _logger;
        private readonly IAphorismsService _aphorismsService;
        private readonly IMapper _mapper;

        public AphorismsController(
            ILogger<AphorismsController> logger,
            IAphorismsService aphorismsService, 
            IMapper mapper)
        {
            _logger = logger;
            _aphorismsService = aphorismsService;
            _mapper = mapper;
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetAphorism(Guid id, string subject)
        {
            var aphorism = await _aphorismsService.GetAphorism(id);

            if (aphorism != null)
            {
                if (!string.IsNullOrEmpty(subject))
                    aphorism.Subject = subject;

                return Ok(_mapper.Map<AphorismDto>(aphorism));
            }
            else
            {
                return NotFound();
            }
        }

        [HttpGet("random")]
        public async Task<IActionResult> GetRandomAphorism(string subject)
        {
            var aphorism = await _aphorismsService.GetRandomAphorism();

            if (aphorism != null)
            {
                if (!string.IsNullOrEmpty(subject))
                    aphorism.Subject = subject;

                return Ok(_mapper.Map<AphorismDto>(aphorism));
            }
            else
            {
                return NotFound();
            }
        }
    }
}

Pages/CreateAphorism.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using AforismiChuckNorris.Data.Entities;
using AforismiChuckNorris.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AforismiChuckNorris.Areas.Identity.Pages.Account
{
    [Authorize]
    public class CreateAphorismModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IAphorismsService _aphorismsService;

        public class InputModel
        {
            [Required]
            public string Aphorism { get; set; }

            [Required]
            public string Culture { get; set; }
        }

        public List<SelectListItem> Cultures { get; } = new List<SelectListItem>
        {
            new SelectListItem { Value = "it-IT", Text = "Italian" },
            new SelectListItem { Value = "en-EN", Text = "English" },
        };

        [BindProperty]
        public InputModel Input { get; set; }

        public CreateAphorismModel(
            UserManager<ApplicationUser> userManager,
            IAphorismsService aphorismsService)
        {
            _userManager = userManager;
            _aphorismsService = aphorismsService;
        }

        public void OnGet()
        {

        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid && !Input.Aphorism.ToLower().Contains("chuck norris"))
            {
                ModelState.AddModelError("Input.Aphorism", "Aphorism must contains \"Chuck Norris\"");
            }

            if (!ModelState.IsValid)
            {
                return Page();
            }

            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            // todo sobstitute chuck norris with {0}
            await _aphorismsService.AddAphorism(Input.Aphorism, Input.Culture, user.Id, true, Data.Models.AphorismStatus.Pending);

            return RedirectToPage("ManageAphorisms");
        }
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ChuckNorrisAphorisms.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using ChuckNorrisAphorisms.Services;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace ChuckNorrisAphorisms.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly IAphorismsService _aphorismsService;
        public int AphorismsCount { get; set; }

        public IndexModel(ILogger<IndexModel> logger, IAphorismsService aphorismsService)
        {
            _logger = logger;
            _aphorismsService = aphorismsService;
        }

        public void OnGet()
        {
            AphorismsCount = _aphorismsService.GetAphorismCount();
        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ChuckNorrisAphorisms.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/CreateAphorism.cshtml
@page
@model AforismiChuckNorris.Areas.Identity.Pages.Account.CreateAphorismModel

@{ 
    Layout = "_LayoutBackoffice";
}

<section>
    <p>Add aphorism:</p>
    <form id="account" method="post">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Input.Aphorism"></label>
            <input asp-for="Input.Aphorism" class="form-control" />
            <span asp-validation-for="Input.Aphorism" class="text-danger"></span>
        </div>
        <div class="form-group">
            <select asp-for="Input.Culture" asp-items="Model.Cultures"></select>
            <span asp-validation-for="Input.Culture" class="text-danger"></span>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Add aphorism</button>
        </div>
    </form>
</section>

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home";
}

<div class="callout">
    <p>Actual number of aphorisms : @Model.AphorismsCount</p>
    <a id="TryItButton" href="#" class="button--primary">Try it now</a>
    <div class="code__block code__block--notabs">
        <pre class="code code--block">
            <code id="ApiOutput"></code>       
        </pre>
    </div>
</div>

<article class="doc__content">
    <section class="js-section">
        <h3 class="section__title">Retrieve a random aphorism in JSON format</h3>
        <samp><a style="word-break: break-all" class="link link--dark" asp-controller="Aphorisms" asp-action="GetRandomAphorism">@Url.ActionLink("GetRandomAphorism", "Aphorisms")</a></samp>
        <p>Example response:</p>
        <div class="code__block code__block--notabs">
            <pre class="code code--block">
            <code>
                    {
                        "id": "49140b30-7341-4523-9af9-540f90bf02f8",
                        "creationDate": "05/01/2021 09:30:50",
                        "updateDate": "05/01/2021 09:30:50",
                        "value": "Quando gli servono una banana flambè, Chuck Norris mangia prima il fuoco"
                    }
                </code>
            </pre>
        </div>
    </section>
    <section class="js-section">
        <h3 class="section__title">Retrieve a specific aphorism by Id</h3>
        <samp>
            <a style="word-break: break-all" class="link link--dark" asp-controller="Aphorisms" asp-action="GetAphorism" asp-route-id="a67a7345-2167-432b-8ef0-89e4b8813ecb">
                @Url.ActionLink("GetAphorism", "Aphorisms", new { Id = "a67a7345-2167-432b-8ef0-89e4b8813ecb" })
            </a>
        </samp>
        <p>Example response:</p>
        <div class="code__block code__block--notabs">
            <pre class="code code--block">
            <code>
                    {
                    "id": "a67a7345-2167-432b-8ef0-89e4b8813ecb",
                    "creationDate": "05/01/2021 11:55:31",
                    "updateDate": "05/01/2021 11:55:31",
                    "value": "Chuck Norris è particolarmente consigliato nelle diete povere di calcio."
                    }
                </code>
            </pre>
        </div>
    </section>
    <section class="js-section">
        <h3 class="section__title">Replace Chuck Norris with a custom name</h3>
        <samp>
            <a style="word-break: break-all" class="link link--dark" asp-controller="Aphorisms" asp-action="GetRandomAphorism" asp-route-subject="John Doe">
                @Url.ActionLink("GetRandomAphorism", "Aphorisms", new { Subject = "John Doe" })
            </a>
        </samp>
        <p>Example response:</p>
        <div class="code__block code__block--notabs">
            <pre class="code code--block">
            <code>
                    {
                        "id": "ae2ac386-fb3a-43a1-90ad-d0a5e6e69e31",
                        "creationDate": "05/01/2021 12:15:04",
                        "updateDate": "05/01/2021 12:15:04",
                        "value": "John Doe è stato campione mondiale di Formula Uno. Senza macchina"
                    }
                </code>
            </pre>
        </div>
    </section>
</article>

@section changelog
{
    <div class="changelog">
        <div class="wrapper">
            <h3 class="section__title">Changelog</h3>
            <div class="changelog__item">
                <div class="changelog__meta">
                    <h4 class="changelog__title">v0.5</h4>
                    <small class="changelog__date">05/01/2021</small>
                </div>
                <div class="changelog__detail">
                    <ul>
                        <li>First release</li>
                        <li>Get seed data from: <a href="https://www.daimon.org/hum/aforismi/aforismi_citazioni_battute_chuck_norris.htm" target="_blank">www.daimon.org</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
}

Pages/ManageAphorisms.cshtml
@page
@model AforismiChuckNorris.Areas.Identity.Pages.Account.ManageAphorismsModel

@{
    Layout = "_LayoutBackoffice";
}

<div class="m-2">    
    <a asp-page="CreateAphorism" class="btn btn-primary mb-3 @(!Model.CanAddAphorisms ? "disabled " : "")">Create</a>
    @{
        string actualpending = Model.PendingAphorisms.Count().ToString();
        string maxPermitted = Model.ApplicationUser.MaxPendingRequest.HasValue ? Model.ApplicationUser.MaxPendingRequest.Value.ToString() : "Unlimited";
        string formattedAviability = $"({actualpending} / {maxPermitted})";
    }

    <h4 class="bg-primary text-white text-center p-2">Your pending aphorisms @formattedAviability </h4>
    <table class="table table-sm table-striped table-bordered">
        <thead>
            <tr>
                <th>AphorismId</th>
                <th>Aphorism</th>
                <th>Date created</th>
                <th>Date updated</th>
                <th>Language</th>
                <th>Status</th>
                <th></th>

            </tr>
        </thead>
        <tbody>
            @foreach (var aphorism in Model.PendingAphorisms)
            {
            <tr>
                <td>@aphorism.Id</td>
                <td>@aphorism.Value</td>
                <td>@aphorism.CreationDate</td>
                <td>@aphorism.UpdateDate</td>
                <td>@aphorism.Culture</td>
                <td>@aphorism.Status</td>
                <td class="text-center">
                    <a asp-page="Edit" asp-route-id="@aphorism.Id"
                       class="btn btn-sm btn-warning">Edit</a>
                    <a asp-page="Delete" asp-route-id="@aphorism.Id"
                       class="btn btn-sm btn-danger">Delete</a>
                </td>
            </tr>
            }
        </tbody>
    </table>

    <h4 class="bg-primary text-white text-center p-2">Your published aphorisms</h4>
    <table class="table table-sm table-striped table-bordered">
        <thead>
            <tr>
                <th>AphorismId</th>
                <th>Aphorism</th>
                <th>Date created</th>
                <th>Date updated</th>
                <th>Status</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var aphorism in Model.PublishedAphorisms)
            {
                <tr>
                    <td>@aphorism.Id</td>
                    <td>@aphorism.Value</td>
                    <td>@aphorism.CreationDate</td>
                    <td>@aphorism.UpdateDate</td>
                    <td>@aphorism.Status</td>
                    <td class="text-center">
                        <a asp-page="Edit" asp-route-id="@aphorism.Id"
                           class="btn btn-sm btn-warning">Edit</a>
                        <a asp-page="Delete" asp-route-id="@aphorism.Id"
                           class="btn btn-sm btn-danger">Delete</a>
                    </td>
                </tr>
            }
        </tbody>

    </table>
</div>